### ISSUE TITLE
Error try exec run.bat

### ISSUE THREAD

**Issue by jesramos** [Jazzmoon/btd6_autoplay#7]
![cmd_Gop6YUd1SH](https://user-images.githubusercontent.com/81809570/142854538-efc5e35f-f7e4-4f6b-91f3-6eff7782459a.png)

**Comment by jesramos** [comment]
> Script should be run from project root, not from scripts directory.

it worked but it says, pytesseract.pytesseract.TesseractNotFoundError: C:\Users\User\AppData\Local\Programs\Tesseract-OCR\tesseract.exe is not installed or it's not in your PATH.

my tesseract is installed in C:\Users\jesrm\AppData\Local\Programs\Tesseract-OCR , for some reason it is not being detected

**Comment by AstroCoding** [comment]
@jesramos Notice how your tesseract is installed under a different user? I left the location path as `C:\Users\User` because you are meant to change the value of `User` to be your user. This means you need the edit the config value at `src/config/settings.json` to be `C:\Users\jesrm\AppData\Local\Programs\Tesseract-OCR\tesseract.exe`.
